config/routes.rb
Rails.application.routes.draw do
  resources :cards
  root 'vozavoz#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  
  def index
    @cards = Card.all
  end
 
  def show
    @card = Card.find(params[:id])
  end
 
  def new
    @card = Card.new
  end

  def create
    @card = Card.new(card_params)
    @card.save
    redirect_to @card
  end

  def card_params
    params.require(:card).permit(:original_text, :translated_text, :review_date)
  end
end

app/controllers/vozavoz_controller.rb
class VozavozController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/index.html.erb
<h1>Listing Cards</h1>

<table>
  <tr>
    <th>Original text</th>
    <th>Translated text</th>
    <th>Review date</th>
    <th colspan="3"></th>
  </tr>
 
  <% @cards.each do |card| %>
    <tr>
      <td><%= card.original_text %></td>
      <td><%= card.translated_text %></td>
      <td><%= card.review_date %></td>
      <td><%= link_to 'Show', card_path(card) %></td>
      <td><%= link_to 'Edit', edit_card_path(card) %></td>
      <td><%= link_to 'Destroy', card_path(card),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/cards/new.html.erb
<h1>New Card</h1>
<%= form_for :card, url: cards_path do |f| %>
  <p>
    <%= f.label :original_text %><br>
    <%= f.text_field :original_text %>
  </p>

  <p>
    <%= f.label :translated_text %><br>
    <%= f.text_field :translated_text %>
  </p>

  <p>
    <%= f.label :review_date %><br>
    <%= f.text_field :review_date %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/cards/show.html.erb
<p>
  <strong>Original text:</strong>
  <%= @card.original_text %>
</p>
 
<p>
  <strong>Translated text:</strong>
  <%= @card.translated_text %>
</p>

<p>
  <strong>Review date:</strong>
  <%= @card.review_date %>
</p>
 
<%= link_to 'Back', cards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flashcards</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section id="container">
      <header class="clearfix">
      
      </header>
      
    </section>

	<nav class="navbar navbar-expand-lg navbar-light bg-light">
	  <a class="navbar-brand" href="<%= root_path%>">Флэшкарточкер</a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>
	  <div class="collapse navbar-collapse" id="navbarNav">
	    <ul class="navbar-nav">
	      <li class="nav-item active">
	        <a class="nav-link" href="<%= cards_path %>">Все карточки <span class="sr-only">(current)</span></a>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link" href="<%= new_card_path %>">Добавить карточку</a>
	      </li>
	    </ul>
	  </div>
	</nav>

    <%= yield %>
  </body>
</html>

app/views/vozavoz/index.html.erb
<section>
      <p style="font-size: 22px;">
        Первый в мире удобный менеджер флеш-карточек. Именно так.
      </p>
    </section>